config/routes.rb
Rottenpotatoes::Application.routes.draw do

  resources :movies
  match 'movies/director/:id' => 'movies#director', :as => :movies_director
  match 'movies/score/:id' => 'movies#score', :as => :movies_score
  match 'movies/viewed_with/:id' => 'movies#viewed_with', :as => :movies_viewed_with
  match '/benchmark/:type' => 'movies#benchmark', :as => :benchmark

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews  
  has_many :moviegoers, :through => :reviews  

def self.all_ratings
    %w(G PG PG-13 NC-17 R)
  end

  def similar_movies
    Movie.find_all_by_director(self.director)
  end
end

app/models/moviegoer.rb
class Moviegoer < ActiveRecord::Base
  validates_presence_of :name
  has_many :reviews
  
  has_many :movies, :through => :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates_presence_of :movie_id
  validates_presence_of :moviegoer_id
  belongs_to :movie
  belongs_to :moviegoer
  validates_inclusion_of :score, :in => [0,1,2,3,4,5]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
 
 caches_page :index
 
  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering,@title_header = {:order => :title}, 'hilite'
    when 'release_date'
      ordering,@date_header = {:order => :release_date}, 'hilite'
    end
    @all_ratings = Movie.all_ratings
    @selected_ratings = params[:ratings] || session[:ratings] || {}

    if @selected_ratings == {}
      @selected_ratings = Hash[@all_ratings.map {|rating| [rating, rating]}]
    end
    
    if params[:sort] != session[:sort]
      session[:sort] = sort
      flash.keep
      redirect_to :sort => sort, :ratings => @selected_ratings and return
    end

    if params[:ratings] != session[:ratings] and @selected_ratings != {}
      session[:sort] = sort
      session[:ratings] = @selected_ratings
      flash.keep
      redirect_to :sort => sort, :ratings => @selected_ratings and return
    end
    @movies = Movie.find_all_by_rating(@selected_ratings.keys, ordering,:limit=>10)
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def director
    @movie = Movie.find(params[:id])
    @director = @movie.director
    if @director.blank?
      flash[:warning] = "'#{@movie.title}' has no director info"
      redirect_to movies_path and return
    end
    @movies = Movie.find_all_by_director(@director)
  end

  def score
    @movie = Movie.find_by_id(params[:id])
    if @movie.blank?
      flash[:warning] = "#{params[:id]} is an invalid id"
      redirect_to movies_path and return
    end
    @reviews = @movie.reviews
    @score=0 
    @score = @reviews.inject(0){|sum,r| sum+r.score}/@reviews.count unless @reviews.empty?   
  end

  def benchmark
    benchType=params[:type]
    @results=[]
    times_to_run=Movie.count/2
    search_movies=Movie.all(:limit=>times_to_run)
    search_goers=Moviegoer.all(:limit=>times_to_run)
    case benchType

    when "movies"
      start_time=Time.now
      search_movies.each do |bench_movie|
         reviews = bench_movie.reviews 
         reviews.each {|r| r}
      end
      total_time=Time.now - start_time
      @results<<{:action => "movie.reviews", :times_run => times_to_run, :time=>total_time.round(5)}
    when "moviegoers"
      start_time=Time.now     
      search_goers.each do |g|
         reviews = g.reviews 
         reviews.each {|r| r}
      end 
      total_time=Time.now - start_time
      @results<<{:action => "moviegoer.reviews", :times_run => times_to_run, :time=>total_time.round(5)}
    end
  end


  def viewed_with
    @movie = Movie.find_by_id(params[:id])
    if @movie.blank?
      flash[:warning] = "#{params[:id]} is an invalid id"
      redirect_to movies_path and return
    end
  
    @moviegoers=@movie.moviegoers(:include => :reviews)
    @similarMovies=[]
    @moviegoers.each do |mg|
      mg.movies.each do |m|
        @similarMovies << m
      end
    
    end
    @similarMovies.uniq!
   end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/benchmark.html.haml
%h1 Benchmark Results

%table#results
  %thead
    %tr
      %th Action Tested
      %th Times Run
      %th Total Time
  %tbody
    - @results.each do |r|
      %tr
        %td #{r[:action]}
        %td #{r[:times_run]}
        %td #{r[:time]}

= link_to 'Movies', movies_path

app/views/movies/director.html.haml
-#  This file is app/views/movies/director.html.haml
%h1 Movies Directed By #{@director}

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :director, 'Director'
  = text_field :movie, :director

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":release_date_sort", true if @date_header
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => 'ratings_submit'

%table#movies
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path
<br/>
= link_to 'Benchmark moviegoer.reviews', benchmark_path(:type=>'moviegoers')
<br/>
= link_to 'Benchmark movie.reviews', benchmark_path(:type=>'movies')

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/score.html.haml
%h1 Average score for #{@movie.title}: #{@score}

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Director:
    = @movie.director
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Average Score for this film', movies_score_path(@movie)
<br/>
= link_to 'Find Movies With Same Director', movies_director_path(@movie)
<br/>
= link_to 'Find movies seen by viewers of this film', movies_viewed_with_path(@movie)
<br/>
= link_to 'Edit', edit_movie_path(@movie)
<br/>
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path

app/views/movies/viewed_with.html.haml
-#  This file is app/views/movies/viewed_with.html.haml
%h1 Movies seen by viewers of #{@movie.title}

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @similarMovies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)